In [64]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))
print(torch.cuda.get_device_capability(0))
torch.set_printoptions(precision=4, sci_mode=False)

2.7.1+cu128
True
NVIDIA GeForce RTX 5090
(12, 0)


# Positional Encoding

In [1]:
import torch
import torch.nn as nn
import math

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [65]:
# Sentence of 5 Tokens
seq_len = 5
d_model = 512
positional_encoding = torch.zeros(seq_len, d_model)
positional_encoding

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [66]:
even_index = torch.arange(0, 512, 2)
odd_index = torch.arange(1, 512, 2)

In [67]:
position = torch.arange(seq_len, dtype=torch.float).unsqueeze(1)
position

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.]])

In [69]:
positional_encoding[:, even_index] += torch.sin(position / (10000 ** (even_index/d_model)))
positional_encoding[:, odd_index] += torch.cos(position / (10000 ** (even_index/d_model)))

In [80]:
positional_encoding[3, :100]

tensor([     0.1411,     -0.9900,      0.2451,     -0.9695,      0.3428,
            -0.9394,      0.4336,     -0.9011,      0.5173,     -0.8558,
             0.5936,     -0.8048,      0.6624,     -0.7491,      0.7239,
            -0.6899,      0.7783,     -0.6279,      0.8257,     -0.5641,
             0.8665,     -0.4992,      0.9010,     -0.4338,      0.9296,
            -0.3685,      0.9528,     -0.3036,      0.9708,     -0.2397,
             0.9842,     -0.1771,      0.9933,     -0.1160,      0.9984,
            -0.0566,      1.0000,      0.0009,      0.9984,      0.0563,
             0.9940,      0.1097,      0.9870,      0.1608,      0.9778,
             0.2098,      0.9666,      0.2565,      0.9536,      0.3010,
             0.9392,      0.3433,      0.9236,      0.3835,      0.9068,
             0.4215,      0.8892,      0.4576,      0.8708,      0.4917,
             0.8518,      0.5238,      0.8324,      0.5542,      0.8126,
             0.5828,      0.7927,      0.6097,     

### This is actually not used. It's converted to Log term in the code, solving too many zeros problem. Derivation Down Below
<div align="center">
<img src="/media/ssd1/UdemyCourses/Transformers-From-Scratch/assets/PE_LogTerm.png" width="800" alt="Positional Encoding Log Term">
</div>

In [90]:
d_model = 512
seq_len = 5

# Create a matrix of shape (seq_len, d_model)
positional_encoding = torch.zeros(seq_len, d_model)

# Temp tensor to help Replicate the formula in the paper
position = torch.arange(seq_len, dtype=torch.float).unsqueeze(1)
even_index = torch.arange(0, d_model, 2)
odd_index = torch.arange(1, d_model, 2)
div_term = torch.exp(even_index * -math.log(10000)/d_model)

# Formula from the paper section 3.5
positional_encoding[:, even_index] += torch.sin(position * div_term)
positional_encoding[:, odd_index] += torch.cos(position * div_term)

In [91]:
positional_encoding

tensor([[     0.0000,      1.0000,      0.0000,  ...,      1.0000,
              0.0000,      1.0000],
        [     0.8415,      0.5403,      0.8219,  ...,      1.0000,
              0.0001,      1.0000],
        [     0.9093,     -0.4161,      0.9364,  ...,      1.0000,
              0.0002,      1.0000],
        [     0.1411,     -0.9900,      0.2451,  ...,      1.0000,
              0.0003,      1.0000],
        [    -0.7568,     -0.6536,     -0.6572,  ...,      1.0000,
              0.0004,      1.0000]])

In [103]:
round(math.sin(1/2 * math.pi), 4)

1.0